"""restructure_student_table

Revision ID: 1327e7a71e64
Revises: 
Create Date: 2025-09-13 17:18:33.618798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1327e7a71e64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_id', table_name='scores')
    op.drop_table('scores')
    op.add_column('students', sa.Column('sbd', sa.String(length=20), nullable=False))
    op.add_column('students', sa.Column('math', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('literature', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('foreign_language', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('physics', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('chemistry', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('biology', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('history', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('geography', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('civic_education', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('foreign_language_code', sa.String(length=10), nullable=True))
    op.drop_index('ix_students_registration_number', table_name='students')
    op.create_index(op.f('ix_students_sbd'), 'students', ['sbd'], unique=True)
    op.drop_column('students', 'full_name')
    op.drop_column('students', 'group_type')
    op.drop_column('students', 'created_at')
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'registration_number')
    op.drop_column('students', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('date_of_birth', sa.DATETIME(), nullable=False))
    op.add_column('students', sa.Column('registration_number', sa.VARCHAR(length=20), nullable=False))
    op.add_column('students', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('students', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('students', sa.Column('group_type', sa.VARCHAR(length=1), nullable=False))
    op.add_column('students', sa.Column('full_name', sa.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_students_sbd'), table_name='students')
    op.create_index('ix_students_registration_number', 'students', ['registration_number'], unique=1)
    op.drop_column('students', 'foreign_language_code')
    op.drop_column('students', 'civic_education')
    op.drop_column('students', 'geography')
    op.drop_column('students', 'history')
    op.drop_column('students', 'biology')
    op.drop_column('students', 'chemistry')
    op.drop_column('students', 'physics')
    op.drop_column('students', 'foreign_language')
    op.drop_column('students', 'literature')
    op.drop_column('students', 'math')
    op.drop_column('students', 'sbd')
    op.create_table('scores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('math', sa.FLOAT(), nullable=False),
    sa.Column('physics', sa.FLOAT(), nullable=False),
    sa.Column('chemistry', sa.FLOAT(), nullable=False),
    sa.Column('literature', sa.FLOAT(), nullable=False),
    sa.Column('english', sa.FLOAT(), nullable=False),
    sa.Column('history', sa.FLOAT(), nullable=True),
    sa.Column('geography', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scores_id', 'scores', ['id'], unique=False)
    # ### end Alembic commands ###
