"""initial_tables

Revision ID: 8492e0f877f0
Revises: 
Create Date: 2025-09-14 14:41:27.049151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8492e0f877f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sbd', sa.String(length=20), nullable=False),
    sa.Column('math', sa.Float(), nullable=True),
    sa.Column('literature', sa.Float(), nullable=True),
    sa.Column('foreign_language', sa.Float(), nullable=True),
    sa.Column('physics', sa.Float(), nullable=True),
    sa.Column('chemistry', sa.Float(), nullable=True),
    sa.Column('biology', sa.Float(), nullable=True),
    sa.Column('history', sa.Float(), nullable=True),
    sa.Column('geography', sa.Float(), nullable=True),
    sa.Column('civic_education', sa.Float(), nullable=True),
    sa.Column('foreign_language_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_sbd'), 'students', ['sbd'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_sbd'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
